repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
          - id: black
            language_version: python3.11.2
    - repo: https://github.com/PyCQA/pylint
      rev: v2.15.3
      hooks:
          - id: pylint
            alias: pylint-py3.8
            name: pylint (py3.8)
            description: This hook checks for pylint issues on python3.
            entry: pylint
            language: python
            language_version: python3.11
            types: [python]

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: "v0.0.278"
      hooks:
          - id: ruff
