version: '3'

volumes:
  bitmenu_local_postgres_data: {}
  bitmenu_local_postgres_data_backups: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: bitmenu_production_postgres
    container_name: bitmenu_local_postgres
    volumes:
      - bitmenu_local_postgres_data:/var/lib/postgresql/data
      - bitmenu_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  docs:
    image: bitmenu_local_docs
    container_name: bitmenu_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./bitmenu:/app/bitmenu:z
    ports:
      - '9000:9000'
    command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: bitmenu_local_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: bitmenu_local_redis
