# Generated by Django 4.2.4 on 2023-08-11 19:52

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_user_first_name_user_last_name_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
